### ISSUE TITLE
Application isn't working

### ISSUE THREAD

**Issue by joessef-102** [Srivats728/driver4vr#1]
so when i downloaded it i did everything as you said but it didn't open and i tried and i tried idk something isn't up so can you try and fix this

**Comment by Srivats728** [comment]
Hello!,
I have looked at your problem and i am going to test and see if i am experiencing the same problem. Remember that this is an app connected to steamVR and make sure you have all of the dependencies needed and hardware capabilities
Thanks
Will look into the problem

**Comment by Srivats728** [comment]
Ok so i have just tested it and i have noticed no issues on my end. Can you make sure any antivirus isnt blocking the software and can you please clarify on what the problem is on "not opening"
Thanks!

**Comment by joessef-102** [comment]
Alr it's the antivirus that blocked me
Thanks for the help

**Comment by joessef-102** [comment]
okay something is up
the antivirus isn't the problem tho
the first time i opened it without the antivirus it worked but the second time just a complete blank
either it's a scam or shit's in my head

**Comment by Srivats728** [comment]
It's a problem with your computer, i am not facing this issue
please make sure you have the hardware requirements and right drivers with a compatible vr streamer and headset
and please do not swear
